name: content
publish_to: 'none'

# ============================================================================ #
# Environment                                                                  #
# ============================================================================ #

environment:
  sdk: '>=2.18.2 <3.0.0'

# ============================================================================ #
# Dependencies                                                                 #
# ============================================================================ #

dependencies:
  flutter:
    sdk: flutter

# ============================================================================ #
# Dev Dependencies                                                             #
# ============================================================================ #

dev_dependencies:
  flutter_lints: ^2.0.0

  core:
    path: ../core

# ============================================================================ #
# Flutter                                                                      #
# ============================================================================ #

flutter:
  uses-material-design: true