name: core
publish_to: 'none'

# ============================================================================ #
# Environment                                                                  #
# ============================================================================ #

environment:
  sdk: '>=2.18.2 <3.0.0'

# ============================================================================ #
# Dependencies                                                                 #
# ============================================================================ #

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: any
  get_it: any
  dio: any
  hive: any
  hive_flutter: any

# ============================================================================ #
# Dev Dependencies                                                             #
# ============================================================================ #

dev_dependencies:
  flutter_lints: ^2.0.0

# ============================================================================ #
# Flutter                                                                      #
# ============================================================================ #

flutter:
  uses-material-design: true