name: theme
publish_to: 'none'

# ============================================================================ #
# Environment                                                                  #
# ============================================================================ #

environment:
  sdk: '>=2.18.2 <3.0.0'

# ============================================================================ #
# Dependencies                                                                 #
# ============================================================================ #

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

# ============================================================================ #
# Dev Dependencies                                                             #
# ============================================================================ #

dev_dependencies:
  flutter_lints: ^2.0.0

# ============================================================================ #
# Flutter                                                                      #
# ============================================================================ #

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/error/
  fonts:
    - family: InterFont
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900