name: home
publish_to: 'none'

# ============================================================================ #
# Environment                                                                  #
# ============================================================================ #

environment:
  sdk: '>=2.18.2 <3.0.0'

# ============================================================================ #
# Dependencies                                                                 #
# ============================================================================ #

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../package/core
  theme:
    path: ../../package/theme
  source:
    path: ../../package/source
  widget:
    path: ../../package/widget

# ============================================================================ #
# Dev Dependencies                                                             #
# ============================================================================ #

dev_dependencies:
  flutter_lints: ^2.0.0

# ============================================================================ #
# Flutter                                                                      #
# ============================================================================ #

flutter:
  uses-material-design: true